# table ====
table <- data.frame(
  phenotype = c("N",
                "Cancer: proximal",
                "Cancer: distal",
                "Cancer: overlapping",
                "Cancer: unspecified",
                
                "morphology: 8010/3",
                "morphology: 8020/3",
                "morphology: 8140/3",
                "morphology: 8144/3",
                "morphology: 8201/3",
                "morphology: 8210/3",
                "morphology: 8211/3",
                "morphology: 8260/3",
                "morphology: 8261/3",
                "morphology: 8263/3",
                "morphology: 8480/3",
                "morphology: 8490/3",
                "morphology: 8510/3",
                
                "Age (years)",
                "SD",
                "Follow-up (years)",
                "SD",
                "Fasting: no",
                "Fasting: inbetween",
                "Fasting: yes",
                "BMI (kg/m2)",
                "SD",
                "Alcohol (g/d)",
                "SD",
                "Smoking: never",
                "Smoking: former",
                "Smoking: current",
                "Smoking: unknown",
                "Education: 1",
                "Education: 2",
                "Education: 3",
                "Education: 4",
                "Education: 5",
                "PA: inactive",
                "PA: moderately inactive",
                "PA: moderately active",
                "PA: active",
                "PA: unknow",
                "Total energy (kcal/d)",
                "SD",
                "Red meat (g/d)",
                "SD",
                "Processed meat (g/d)",
                "SD",
                "Fibre (g/d)",
                "SD"),
  ## total ====
  total = c(nrow(data),
            table(data$Siteclrt)[[2]] + table(data$Siteclrt)[[3]] + table(data$Siteclrt)[[4]] + table(data$Siteclrt)[[5]] + table(data$Siteclrt)[[6]] + table(data$Siteclrt)[[7]],
            table(data$Siteclrt)[[8]] + table(data$Siteclrt)[[9]],
            table(data$Siteclrt)[[10]],
            table(data$Siteclrt)[[11]],
            
            table(data$Morpclrt)[[2]],
            table(data$Morpclrt)[[3]],
            table(data$Morpclrt)[[4]],
            table(data$Morpclrt)[[5]],
            table(data$Morpclrt)[[6]],
            table(data$Morpclrt)[[7]],
            table(data$Morpclrt)[[8]],
            table(data$Morpclrt)[[9]],
            table(data$Morpclrt)[[10]],
            table(data$Morpclrt)[[11]],
            table(data$Morpclrt)[[12]],
            table(data$Morpclrt)[[13]],
            table(data$Morpclrt)[[14]],
            
            round(mean(data$Age_Blood),2),
            round(sd(data$Age_Blood),2),
            round(mean(data$Length_Bld_years),2),
            round(sd(data$Length_Bld_years),2),
            table(data$Fasting_C)[[1]],
            table(data$Fasting_C)[[2]],
            table(data$Fasting_C)[[3]],
            round(mean(data$Bmi_C),2),
            round(sd(data$Bmi_C),2),
            round(mean(data$Alc_Re, na.rm = T),2),
            round(sd(data$Alc_Re, na.rm = T),2),
            table(data$Smoke_Stat)[[1]],
            table(data$Smoke_Stat)[[2]],
            table(data$Smoke_Stat)[[3]],
            table(data$Smoke_Stat)[[4]],
            table(data$L_School)[[1]],
            table(data$L_School)[[2]],
            table(data$L_School)[[3]],
            table(data$L_School)[[4]],
            table(data$L_School)[[5]],
            table(data$Pa_Index)[[1]],
            table(data$Pa_Index)[[2]],
            table(data$Pa_Index)[[3]],
            table(data$Pa_Index)[[4]],
            table(data$Pa_Index)[[5]],
            round(mean(data$QE_ENERGY, na.rm = T),2),
            round(sd(data$QE_ENERGY, na.rm = T),2),
            round(mean(data$QgE0701, na.rm = T),2),
            round(sd(data$QgE0701, na.rm = T),2),
            round(mean(data$QgE0704, na.rm = T),2),
            round(sd(data$QgE0704, na.rm = T),2),
            round(mean(data$QE_FIBT, na.rm = T),2),
            round(sd(data$QE_FIBT, na.rm = T),2)),
  
  ## male ====
  male = c(nrow(male),
           table(male$Siteclrt)[[2]] + table(male$Siteclrt)[[3]] + table(male$Siteclrt)[[4]] + table(male$Siteclrt)[[5]] + table(male$Siteclrt)[[6]] + table(male$Siteclrt)[[7]],
           table(male$Siteclrt)[[8]] + table(male$Siteclrt)[[9]],
           table(male$Siteclrt)[[10]],
           table(male$Siteclrt)[[11]],
           
           table(data$Morpclrt, data$Sex)[2,1],
           table(data$Morpclrt, data$Sex)[3,1],
           table(data$Morpclrt, data$Sex)[4,1],
           table(data$Morpclrt, data$Sex)[5,1],
           table(data$Morpclrt, data$Sex)[6,1],
           table(data$Morpclrt, data$Sex)[7,1],
           table(data$Morpclrt, data$Sex)[8,1],
           table(data$Morpclrt, data$Sex)[9,1],
           table(data$Morpclrt, data$Sex)[10,1],
           table(data$Morpclrt, data$Sex)[11,1],
           table(data$Morpclrt, data$Sex)[12,1],
           table(data$Morpclrt, data$Sex)[13,1],
           table(data$Morpclrt, data$Sex)[14,1],
           
           round(mean(male$Age_Blood),2),
           round(sd(male$Age_Blood),2),
           round(mean(male$Length_Bld_years),2),
           round(sd(male$Length_Bld_years),2),
           table(male$Fasting_C)[[1]],
           table(male$Fasting_C)[[2]],
           table(male$Fasting_C)[[3]],
           round(mean(male$Bmi_C),2),
           round(sd(male$Bmi_C),2),
           round(mean(male$Alc_Re, na.rm = T),2),
           round(sd(male$Alc_Re, na.rm = T),2),
           table(male$Smoke_Stat)[[1]],
           table(male$Smoke_Stat)[[2]],
           table(male$Smoke_Stat)[[3]],
           table(male$Smoke_Stat)[[4]],
           table(male$L_School)[[1]],
           table(male$L_School)[[2]],
           table(male$L_School)[[3]],
           table(male$L_School)[[4]],
           table(male$L_School)[[5]],
           table(male$Pa_Index)[[1]],
           table(male$Pa_Index)[[2]],
           table(male$Pa_Index)[[3]],
           table(male$Pa_Index)[[4]],
           table(male$Pa_Index)[[5]],
           round(mean(male$QE_ENERGY, na.rm = T),2),
           round(sd(male$QE_ENERGY, na.rm = T),2),
           round(mean(male$QgE0701, na.rm = T),2),
           round(sd(male$QgE0701, na.rm = T),2),
           round(mean(male$QgE0704, na.rm = T),2),
           round(sd(male$QgE0704, na.rm = T),2),
           round(mean(male$QE_FIBT, na.rm = T),2),
           round(sd(male$QE_FIBT, na.rm = T),2)),
  
  ### case ====
  male_case = c(nrow(male_case),
                "NA",
                "NA",
                "NA",
                "NA",
                
                table(data$Morpclrt, data$Sex)[2,1],
                table(data$Morpclrt, data$Sex)[3,1],
                table(data$Morpclrt, data$Sex)[4,1],
                table(data$Morpclrt, data$Sex)[5,1],
                table(data$Morpclrt, data$Sex)[6,1],
                table(data$Morpclrt, data$Sex)[7,1],
                table(data$Morpclrt, data$Sex)[8,1],
                table(data$Morpclrt, data$Sex)[9,1],
                table(data$Morpclrt, data$Sex)[10,1],
                table(data$Morpclrt, data$Sex)[11,1],
                table(data$Morpclrt, data$Sex)[12,1],
                table(data$Morpclrt, data$Sex)[13,1],
                table(data$Morpclrt, data$Sex)[14,1],
                
                round(mean(male_case$Age_Blood),2),
                round(sd(male_case$Age_Blood),2),
                round(mean(male_case$Length_Bld_years),2),
                round(sd(male_case$Length_Bld_years),2),
                table(male_case$Fasting_C)[[1]],
                table(male_case$Fasting_C)[[2]],
                table(male_case$Fasting_C)[[3]],
                round(mean(male_case$Bmi_C),2),
                round(sd(male_case$Bmi_C),2),
                round(mean(male_case$Alc_Re, na.rm = T),2),
                round(sd(male_case$Alc_Re, na.rm = T),2),
                table(male_case$Smoke_Stat)[[1]],
                table(male_case$Smoke_Stat)[[2]],
                table(male_case$Smoke_Stat)[[3]],
                table(male_case$Smoke_Stat)[[4]],
                table(male_case$L_School)[[1]],
                table(male_case$L_School)[[2]],
                table(male_case$L_School)[[3]],
                table(male_case$L_School)[[4]],
                table(male_case$L_School)[[5]],
                table(male_case$Pa_Index)[[1]],
                table(male_case$Pa_Index)[[2]],
                table(male_case$Pa_Index)[[3]],
                table(male_case$Pa_Index)[[4]],
                table(male_case$Pa_Index)[[5]],
                round(mean(male_case$QE_ENERGY, na.rm = T),2),
                round(sd(male_case$QE_ENERGY, na.rm = T),2),
                round(mean(male_case$QgE0701, na.rm = T),2),
                round(sd(male_case$QgE0701, na.rm = T),2),
                round(mean(male_case$QgE0704, na.rm = T),2),
                round(sd(male_case$QgE0704, na.rm = T),2),
                round(mean(male_case$QE_FIBT, na.rm = T),2),
                round(sd(male_case$QE_FIBT, na.rm = T),2)),
  
  ### control ====
  male_control = c(nrow(male_control),
                   "NA",
                   "NA",
                   "NA",
                   "NA",
                   
                   "NA",
                   "NA",
                   "NA",
                   "NA",
                   "NA",
                   "NA",
                   "NA",
                   "NA",
                   "NA",
                   "NA",
                   "NA",
                   "NA",
                   "NA",
                   
                   round(mean(male_control$Age_Blood),2),
                   round(sd(male_control$Age_Blood),2),
                   round(mean(male_control$Length_Bld_years),2),
                   round(sd(male_control$Length_Bld_years),2),
                   table(male_control$Fasting_C)[[1]],
                   table(male_control$Fasting_C)[[2]],
                   table(male_control$Fasting_C)[[3]],
                   round(mean(male_control$Bmi_C),2),
                   round(sd(male_control$Bmi_C),2),
                   round(mean(male_control$Alc_Re, na.rm = T),2),
                   round(sd(male_control$Alc_Re, na.rm = T),2),
                   table(male_control$Smoke_Stat)[[1]],
                   table(male_control$Smoke_Stat)[[2]],
                   table(male_control$Smoke_Stat)[[3]],
                   table(male_control$Smoke_Stat)[[4]],
                   table(male_control$L_School)[[1]],
                   table(male_control$L_School)[[2]],
                   table(male_control$L_School)[[3]],
                   table(male_control$L_School)[[4]],
                   table(male_control$L_School)[[5]],
                   table(male_control$Pa_Index)[[1]],
                   table(male_control$Pa_Index)[[2]],
                   table(male_control$Pa_Index)[[3]],
                   table(male_control$Pa_Index)[[4]],
                   table(male_control$Pa_Index)[[5]],
                   round(mean(male_control$QE_ENERGY, na.rm = T),2),
                   round(sd(male_control$QE_ENERGY, na.rm = T),2),
                   round(mean(male_control$QgE0701, na.rm = T),2),
                   round(sd(male_control$QgE0701, na.rm = T),2),
                   round(mean(male_control$QgE0704, na.rm = T),2),
                   round(sd(male_control$QgE0704, na.rm = T),2),
                   round(mean(male_control$QE_FIBT, na.rm = T),2),
                   round(sd(male_control$QE_FIBT, na.rm = T),2)),
  
  ## female ====
  female = c(nrow(female),
             table(female$Siteclrt)[[2]] + table(female$Siteclrt)[[3]] + table(female$Siteclrt)[[4]] + table(female$Siteclrt)[[5]] + table(female$Siteclrt)[[6]] + table(female$Siteclrt)[[7]],
             table(female$Siteclrt)[[8]] + table(female$Siteclrt)[[9]],
             table(female$Siteclrt)[[10]],
             table(female$Siteclrt)[[11]],
             
             table(data$Morpclrt, data$Sex)[2,2],
             table(data$Morpclrt, data$Sex)[3,2],
             table(data$Morpclrt, data$Sex)[4,2],
             table(data$Morpclrt, data$Sex)[5,2],
             table(data$Morpclrt, data$Sex)[6,2],
             table(data$Morpclrt, data$Sex)[7,2],
             table(data$Morpclrt, data$Sex)[8,2],
             table(data$Morpclrt, data$Sex)[9,2],
             table(data$Morpclrt, data$Sex)[10,2],
             table(data$Morpclrt, data$Sex)[11,2],
             table(data$Morpclrt, data$Sex)[12,2],
             table(data$Morpclrt, data$Sex)[13,2],
             table(data$Morpclrt, data$Sex)[14,2],
             
             round(mean(female$Age_Blood),2),
             round(sd(female$Age_Blood),2),
             round(mean(female$Length_Bld_years),2),
             round(sd(female$Length_Bld_years),2),
             table(female$Fasting_C)[[1]],
             table(female$Fasting_C)[[2]],
             table(female$Fasting_C)[[3]],
             round(mean(female$Bmi_C),2),
             round(sd(female$Bmi_C),2),
             round(mean(female$Alc_Re, na.rm = T),2),
             round(sd(female$Alc_Re, na.rm = T),2),
             table(female$Smoke_Stat)[[1]],
             table(female$Smoke_Stat)[[2]],
             table(female$Smoke_Stat)[[3]],
             table(female$Smoke_Stat)[[4]],
             table(female$L_School)[[1]],
             table(female$L_School)[[2]],
             table(female$L_School)[[3]],
             table(female$L_School)[[4]],
             table(female$L_School)[[5]],
             table(female$Pa_Index)[[1]],
             table(female$Pa_Index)[[2]],
             table(female$Pa_Index)[[3]],
             table(female$Pa_Index)[[4]],
             table(female$Pa_Index)[[5]],
             round(mean(female$QE_ENERGY, na.rm = T),2),
             round(sd(female$QE_ENERGY, na.rm = T),2),
             round(mean(female_case$QgE0701, na.rm = T),2),
             round(sd(female$QgE0701, na.rm = T),2),
             round(mean(female$QgE0704, na.rm = T),2),
             round(sd(female$QgE0704, na.rm = T),2),
             round(mean(female$QE_FIBT, na.rm = T),2),
             round(sd(female$QE_FIBT, na.rm = T),2)),
  
  ### case ====
  female_case = c(nrow(female_case),
                  "NA",
                  "NA",
                  "NA",
                  "NA",
                  
                  table(data$Morpclrt, data$Sex)[2,2],
                  table(data$Morpclrt, data$Sex)[3,2],
                  table(data$Morpclrt, data$Sex)[4,2],
                  table(data$Morpclrt, data$Sex)[5,2],
                  table(data$Morpclrt, data$Sex)[6,2],
                  table(data$Morpclrt, data$Sex)[7,2],
                  table(data$Morpclrt, data$Sex)[8,2],
                  table(data$Morpclrt, data$Sex)[9,2],
                  table(data$Morpclrt, data$Sex)[10,2],
                  table(data$Morpclrt, data$Sex)[11,2],
                  table(data$Morpclrt, data$Sex)[12,2],
                  table(data$Morpclrt, data$Sex)[13,2],
                  table(data$Morpclrt, data$Sex)[14,2],
                  
                  round(mean(female_case$Age_Blood),2),
                  round(sd(female_case$Age_Blood),2),
                  round(mean(female_case$Length_Bld_years),2),
                  round(sd(female_case$Length_Bld_years),2),
                  table(female_case$Fasting_C)[[1]],
                  table(female_case$Fasting_C)[[2]],
                  table(female_case$Fasting_C)[[3]],
                  round(mean(female_case$Bmi_C),2),
                  round(sd(female_case$Bmi_C),2),
                  round(mean(female_case$Alc_Re, na.rm = T),2),
                  round(sd(female_case$Alc_Re, na.rm = T),2),
                  table(female_case$Smoke_Stat)[[1]],
                  table(female_case$Smoke_Stat)[[2]],
                  table(female_case$Smoke_Stat)[[3]],
                  table(female_case$Smoke_Stat)[[4]],
                  table(female_case$L_School)[[1]],
                  table(female_case$L_School)[[2]],
                  table(female_case$L_School)[[3]],
                  table(female_case$L_School)[[4]],
                  table(female_case$L_School)[[5]],
                  table(female_case$Pa_Index)[[1]],
                  table(female_case$Pa_Index)[[2]],
                  table(female_case$Pa_Index)[[3]],
                  table(female_case$Pa_Index)[[4]],
                  table(female_case$Pa_Index)[[5]],
                  round(mean(female_case$QE_ENERGY, na.rm = T),2),
                  round(sd(female_case$QE_ENERGY, na.rm = T),2),
                  round(mean(female_case$QgE0701, na.rm = T),2),
                  round(sd(female_case$QgE0701, na.rm = T),2),
                  round(mean(female_case$QgE0704, na.rm = T),2),
                  round(sd(female_case$QgE0704, na.rm = T),2),
                  round(mean(female_case$QE_FIBT, na.rm = T),2),
                  round(sd(female_case$QE_FIBT, na.rm = T),2)),
  
  ## control ====
  female_control = c(nrow(female_control),
                     "NA",
                     "NA",
                     "NA",
                     "NA",
                     
                     "NA",
                     "NA",
                     "NA",
                     "NA",
                     "NA",
                     "NA",
                     "NA",
                     "NA",
                     "NA",
                     "NA",
                     "NA",
                     "NA",
                     "NA",
                     
                     round(mean(female_control$Age_Blood),2),
                     round(sd(female_control$Age_Blood),2),
                     round(mean(female_control$Length_Bld_years),2),
                     round(sd(female_control$Length_Bld_years),2),
                     table(female_control$Fasting_C)[[1]],
                     table(female_control$Fasting_C)[[2]],
                     table(female_control$Fasting_C)[[3]],
                     round(mean(female_control$Bmi_C),2),
                     round(sd(female_control$Bmi_C),2),
                     round(mean(female_control$Alc_Re, na.rm = T),2),
                     round(sd(female_control$Alc_Re, na.rm = T),2),
                     table(female_control$Smoke_Stat)[[1]],
                     table(female_control$Smoke_Stat)[[2]],
                     table(female_control$Smoke_Stat)[[3]],
                     table(female_control$Smoke_Stat)[[4]],
                     table(female_control$L_School)[[1]],
                     table(female_control$L_School)[[2]],
                     table(female_control$L_School)[[3]],
                     table(female_control$L_School)[[4]],
                     table(female_control$L_School)[[5]],
                     table(female_control$Pa_Index)[[1]],
                     table(female_control$Pa_Index)[[2]],
                     table(female_control$Pa_Index)[[3]],
                     table(female_control$Pa_Index)[[4]],
                     table(female_control$Pa_Index)[[5]],
                     round(mean(female_control$QE_ENERGY, na.rm = T),2),
                     round(sd(female_control$QE_ENERGY, na.rm = T),2),
                     round(mean(female_control$QgE0701, na.rm = T),2),
                     round(sd(female_control$QgE0701, na.rm = T),2),
                     round(mean(female_control$QgE0704, na.rm = T),2),
                     round(sd(female_control$QgE0704, na.rm = T),2),
                     round(mean(female_control$QE_FIBT, na.rm = T),2),
                     round(sd(female_control$QE_FIBT, na.rm = T),2))
)

# save ====
write.table(table, "analysis/tables/descriptives_pos_morph.txt", 
            row.names = FALSE, col.names = TRUE, quote = FALSE, sep = "\t")
